version: '3.8'

services:
  falai-mcp:
    build: .
    # Port mapping'i kaldırıyoruz - sadece internal network'te erişilebilir
    expose:
      - "18888"
    environment:
      - FALAI_ENABLE_HTTP=true
      - FALAI_HTTP_HOST=0.0.0.0
      - FALAI_HTTP_PORT=18888
      - FALAI_REQUEST_TIMEOUT=120
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - internal-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:18888/mcp/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  internal-network:
    driver: bridge
    internal: true
